---
- name: Setup and verify local environment
  hosts: local
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Verify Docker is running
      command: docker ps
      register: docker_output
      changed_when: false

    - debug:
        var: docker_output.stdout_lines
